// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Novvi.Infrastructure.Persistence;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Novvi.Infrastructure.Migrations
{
    [DbContext(typeof(NovviContext))]
    partial class NovviContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Novvi.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ENDERECOS", (string)null);
                });

            modelBuilder.Entity("Novvi.Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FUNCIONARIOS", (string)null);
                });

            modelBuilder.Entity("Novvi.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("IdPedido")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("TipoPagamento")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("IdPedido")
                        .IsUnique();

                    b.ToTable("PAGAMENTOS", (string)null);
                });

            modelBuilder.Entity("Novvi.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("Frete")
                        .HasColumnType("NUMBER(18,2)");

                    b.Property<Guid>("IdFuncionario")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("IdFuncionario");

                    b.HasIndex("IdUsuario");

                    b.ToTable("PEDIDOS", (string)null);
                });

            modelBuilder.Entity("Novvi.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PRODUTOS", (string)null);
                });

            modelBuilder.Entity("Novvi.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("PedidoProduto", b =>
                {
                    b.Property<Guid>("PedidosId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ProdutosId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("PedidosId", "ProdutosId");

                    b.HasIndex("ProdutosId");

                    b.ToTable("PEDIDO_PRODUTO", (string)null);
                });

            modelBuilder.Entity("Novvi.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("Novvi.Domain.Entities.Usuario", null)
                        .WithMany("Enderecos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Novvi.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("Novvi.Domain.Entities.Pedido", null)
                        .WithOne("Pagamento")
                        .HasForeignKey("Novvi.Domain.Entities.Pagamento", "IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Novvi.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("Novvi.Domain.Entities.Funcionario", null)
                        .WithMany("PedidosRealizados")
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Novvi.Domain.Entities.Usuario", null)
                        .WithMany("HistoricoPedidos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PedidoProduto", b =>
                {
                    b.HasOne("Novvi.Domain.Entities.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Novvi.Domain.Entities.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Novvi.Domain.Entities.Funcionario", b =>
                {
                    b.Navigation("PedidosRealizados");
                });

            modelBuilder.Entity("Novvi.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("Novvi.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Enderecos");

                    b.Navigation("HistoricoPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
